# -*- coding: utf-8 -*-
"""Python + SQL Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZyXfX1hGxyC3GKaxh8Pih2GB3I6C_n4J
"""

#read data from the file and handle null values

import pandas as pd
df = pd.read_csv('orders.csv',na_values=['Not Available','unknown'])
df['Ship Mode'].unique()

#rename columns names ..make them lower case and replace space with underscore

df.rename(columns={'Order Id':'order_id', 'City':'city'})
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df.head(5)

#derive new columns discount , sale price and profit

df['discount']=df['list_price']*df['discount_percent']*.01
df['sale_price']= df['list_price']-df['discount']
df['profit']=df['sale_price']-df['cost_price']
df

#convert order date from object data type to datetime

df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")
df

#drop cost price list price and discount percent columns

columns_to_drop = ['list_price', 'cost_price', 'discount_percent']
for column in columns_to_drop:
    if column in df.columns:
        df.drop(columns=[column], inplace=True)
    else:
        print(f"Column '{column}' not found in DataFrame. Skipping.")
df